#!/bin/env bash

# TODO: Add the cargo and wasmtime checks/installs


if command -v cargo > /dev/null 2>&1; then
    echo "Cargo Installed!"
else
    echo "Installing Cargo..."
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    echo "source $HOME/.cargo/env" >> $HOME/.bashrc
fi

source $HOME/.cargo/env

if command -v wasmtime > /dev/null 2>&1; then
    echo "Wasmtime Installed!"
else
    echo "Installing Wasmtime!"
    curl https://wasmtime.dev/install.sh -sSf | bash
fi

cargo component build --quiet

wasmtime serve -Scommon -Sallow-ip-name-lookup -Stcp -Sudp -Sinherit-network -Spreview0 -Spreview2 -Shttp -Wall-proposals -Ddebug-info -Dlogging --dir=. ./target/wasm32-wasip1/debug/gram.wasm

